### ISSUE TITLE
this.contentDocument is null for safari mobile safari

### ISSUE THREAD

**Issue by sergey-lapin** [KyleAMathews/element-resize-event#13]
I am having this error for safari/mobile safari 

```
TypeError: null is not an object (evaluating 'this.contentDocument.defaultView')
```
I will keep debugging

**Comment by munkyjunky** [comment]
Had the same issue in Chrome 57 on Mac OS, in a React JS project.

Error occurred when calling `unbind` in `componentWillUnmount` - notably though this only occurred after switching my project from React 15.3.1 to Inferno 1.6.2. It seems to be an issue with either my code or Inferno in my case - by the time `unbind` is being called the element has been removed from the DOM. 

For me it's specifically this line from `unbind` that is breaking:
```
# element-resize-event/blob/131c4d6fd01b6bd4a19d9698d37022b300fc2f51/index.js#L104
delete element.__resizeTrigger__.contentDocument.defaultView.__resizeTrigger__
```

I'm not sure if this is something that should be handled by the `unbind` function, but hopefully this information will be useful for any other devs encountering this problem.

**Comment by mittalabhas1** [comment]
I'm facing the same issue after upgrading to React 16. Is there any solution for this yet @KyleAMathews ?

**Comment by shablenko** [comment]
Same in Firefox 46.0 and React 16

**Comment by windok** [comment]
facing the problem when listener is set to an element in component and the whole component is unmounted.
When just resize element in component is inserted/removed (ref changes) then works just fine.
React 16.2

**Comment by crazytoucan** [comment]
(Not a maintainer) It's possible this issue was fixed in https://github.com/KyleAMathews/element-resize-event/pull/28 , but as far as I understand there hasn't been a release of the package since then.

Is anybody available to cut a release? Separately, has anybody verified that fix?

**Comment by tirli** [comment]
No, seems like #28 does not help. Tried to use version from the master. But it still fails with error 
`Cannot read property 'defaultView' of null` in line `element.__resizeTrigger__.contentDocument.defaultView.removeEventListener` in unbind.
